/**
 * Miljøvariabler for Korportal - MAL
 *
 * Kopier denne filen til js/env.js og fyll inn faktiske Power Automate URL-er.
 * js/env.js er i .gitignore og blir ikke committet.
 *
 * URL-format fra Power Automate HTTP-trigger:
 * https://prod-xx.westeurope.logic.azure.com:443/workflows/.../triggers/manual/paths/invoke?api-version=...&sp=...&sv=...&sig=...
 */
window.ENV = {
    POWER_AUTOMATE_NAVIGATION_URL: '',
    POWER_AUTOMATE_ANNOUNCEMENTS_URL: '',
    POWER_AUTOMATE_QUICKLINKS_URL: '',
    POWER_AUTOMATE_CONCERTS_URL: '',
    POWER_AUTOMATE_TICKET_RESERVATIONS_URL: '',
    POWER_AUTOMATE_PRACTICE_URL: '',
    POWER_AUTOMATE_ARTICLES_URL: '',
    POWER_AUTOMATE_CONTACTS_URL: '',
    POWER_AUTOMATE_MESSAGES_URL: '',
    POWER_AUTOMATE_MESSAGE_COMMENTS_URL: '',
    POWER_AUTOMATE_POSTS_URL: '',
    POWER_AUTOMATE_CREATE_POST_URL: '',
    POWER_AUTOMATE_POST_COMMENTS_URL: '',
    POWER_AUTOMATE_DOWNLOADS_URL: '',
    POWER_AUTOMATE_MUSIC_URL: '',
    POWER_AUTOMATE_TICKET_ADMIN_URL: '',
    POWER_AUTOMATE_TICKET_ADMIN_UPDATE_URL: '',
    POWER_AUTOMATE_TICKET_ADMIN_DELETE_URL: '',
    POWER_AUTOMATE_PROFILE_URL: '',
    POWER_AUTOMATE_PROFILE_UPDATE_URL: '',
    POWER_AUTOMATE_MEMBERS_PAGE_URL: '',
    POWER_AUTOMATE_MEMBERS_PAGE_RSVP_URL: '',
    POWER_AUTOMATE_AUTH_SEND_CODE_URL: '',
    POWER_AUTOMATE_AUTH_VERIFY_CODE_URL: '',
    POWER_AUTOMATE_TICKET_VALIDATE_URL: '',
    POWER_AUTOMATE_PRACTICE_PAGETURNS_URL: '',
    POWER_AUTOMATE_CREATE_MESSAGE_URL: '',
    POWER_AUTOMATE_CREATE_EVENT_URL: '',
    POWER_AUTOMATE_FILES_URL: '',
    POWER_AUTOMATE_FILES_UPDATE_URL: '',
    POWER_AUTOMATE_BLOB_CLEAR_URL: '',
    POWER_AUTOMATE_BLOB_UPLOAD_URL: '',
    POWER_AUTOMATE_FILES_UPLOAD_URL: '',
    POWER_AUTOMATE_STYRE_MEMBERS_URL: '',
    POWER_AUTOMATE_STYRE_REGISTER_MEMBER_URL: '',
    POWER_AUTOMATE_STYRE_UPDATE_MEMBER_URL: '',
    POWER_AUTOMATE_STYRE_DELETE_MEMBER_URL: '',
    POWER_AUTOMATE_STYRE_SEND_EMAIL_URL: '',
};
